# Generated by Django 5.1.3 on 2024-11-26 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('helados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.IntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('finalizado', 'Finalizado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(blank=True, max_length=10, unique=True)),
                ('helados', models.ManyToManyField(related_name='boletas', to='helados.helado')),
            ],
        ),
    ]
