# Generated by Django 5.1.3 on 2024-11-27 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helados', '0001_initial'),
        ('pedidos', '0002_alter_boleta_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boleta',
            old_name='cliente_id',
            new_name='id_cliente',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='helados',
        ),
        migrations.AlterField(
            model_name='boleta',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesado', 'Procesado'), ('finalizado', 'Finalizado')], max_length=10),
        ),
        migrations.CreateModel(
            name='BoletaDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=5, unique=True)),
                ('cantidad', models.SmallIntegerField()),
                ('id_boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='pedidos.boleta')),
                ('id_helado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='helados.helado')),
            ],
        ),
    ]
