# Generated by Django 5.1.3 on 2024-11-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_rename_cliente_id_boleta_id_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contrasena', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='boleta',
            name='id_cliente',
        ),
        migrations.AlterField(
            model_name='boletadetalle',
            name='id_boleta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.boleta'),
        ),
        migrations.AddField(
            model_name='boleta',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.cliente'),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pedidos.boleta')),
            ],
        ),
    ]
