# Generated by Django 5.1.3 on 2024-11-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_cliente_remove_boleta_id_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadetalle',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
    ]
