# Generated by Django 5.1.3 on 2024-12-02 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_boletadetalle_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boletadetalle',
            name='codigo',
            field=models.IntegerField(),
        ),
    ]
